version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/core/backend
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start