# Generated by Django 4.1.7 on 2023-03-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_category_id_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
    ]
