# Generated by Django 3.2.18 on 2023-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
