# Generated by Django 4.1.7 on 2023-03-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_category_id_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subcomment',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='subcomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
